import Navbar from "./components/Navbar";
import "../globals.css";
import { cookies } from "next/headers";

export const metadata = {
  title: "Nest",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookie = await cookies();
  const myCookie = cookie.get("accessToken")?.value;

 async function profileData() {
   const res = await fetch("https://fdr-food-api.onrender.com/api/profile", {
     method: "GET",
     headers: {
       Authorization: `Bearer ${myCookie}`,
     },
     cache: "no-store",
   });
   return await res.json();
 }

 const res = await profileData();
  const userData = res.user;

  return (
    <html lang="en">
      <body>
        <Navbar userData={userData} />
        {children}
      </body>
    </html>
  );
}
