import { cookies } from "next/headers";
import Navbar from "../(main)/components/Navbar";
import "../globals.css";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookie = await cookies();
  const myCookie = cookie.get("accessToken")?.value;

  if (myCookie) {
    return redirect("/")
  }
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
